language: node_js
node_js:
  - stable

install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install -g coveralls
  - npm install

script:
  - npm run build
  - npm run test

after_success:
  - export CURRENT_VERSION=$(node -p "require('./package.json').version")
  - export LATEST=$(npm view $(node -p "require('./package.json').name") dist-tags.latest)
  - export NEXT=$(npm view $(node -p "require('./package.json').name") dist-tags.next)
  - npm run coverage && cat coverage/lcov.info | coveralls

before_deploy:
  - if [ "$LATEST" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "on master branch"; export TRAVIS_TAG=v$CURRENT_VERSION; fi;
  - if [ "$NEXT" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "develop" ]; then echo
    "on develop branch"; export TRAVIS_TAG=v$CURRENT_VERSION-next; fi;

deploy:
  - provider: releases
    api_key:
      secure: dr8ChsYYvTQRNVhVu2uv44yoS0woKi6HXvCo0VhVrdS86YqQ0PRcdfwUz8mQrG3OuJUUMe1fJjZmZQ/1m30g5b6fmnIoyk2cURdN1ntzE+0cRMv2kO94RJvGw8RFeAFJvCzOUDXYFneBrcqWfltAMeEck1LKbKlzB83stqBg3urw4u9Im/fD6w2IM3m903gTFj4naqJm3myQCFCYz3uOWTSe/fCU2vaFPxdl2LtSVfGM1ckLc7nKl7E0e32Or3yKtk/xI2G/zsJBuqZD99xoQ2/mlzlDLmKcjEFyhzS7RVFInleQeTB+uBP2lFua1uwoi/N6J0wXWI+9E7+Tuu89D3NMTDEza9KAz//RKFqVGsOjzvv8x8EzljY3vmDglC4kjQjbd6fp+3VUmQgB+NwUPnN/n/hbhDZ27Q35oLp/xAl9/eiFaCO5dgvJ48NS4jQMNQTnM7RJilAQLuRo9+iCsY0u+PjbCjXB/TIyE/hqEkjOKKwyTWpscMkL9mrqUHP0ZTkoLE+QGkQWbTueBy27X6BB+F9LocOwNX4eAbROKP8dFlbKbBbWXdEy04mTBCwqjAJeF3I6kvCmo2URP55Jn0v4eex8gZxJcHnuAtmz0jD3kjHJdAwuJAcIaxiHEQc6gQ/b+XvmBNIxLuP8M+2ON+76NnrvKumV/z5uW0AyUHA=
    on:
      tags: true
      repo: james-lim/coin-verse
      branch: master
  - provider: releases
    prerelease: true
    api_key:
      secure: dr8ChsYYvTQRNVhVu2uv44yoS0woKi6HXvCo0VhVrdS86YqQ0PRcdfwUz8mQrG3OuJUUMe1fJjZmZQ/1m30g5b6fmnIoyk2cURdN1ntzE+0cRMv2kO94RJvGw8RFeAFJvCzOUDXYFneBrcqWfltAMeEck1LKbKlzB83stqBg3urw4u9Im/fD6w2IM3m903gTFj4naqJm3myQCFCYz3uOWTSe/fCU2vaFPxdl2LtSVfGM1ckLc7nKl7E0e32Or3yKtk/xI2G/zsJBuqZD99xoQ2/mlzlDLmKcjEFyhzS7RVFInleQeTB+uBP2lFua1uwoi/N6J0wXWI+9E7+Tuu89D3NMTDEza9KAz//RKFqVGsOjzvv8x8EzljY3vmDglC4kjQjbd6fp+3VUmQgB+NwUPnN/n/hbhDZ27Q35oLp/xAl9/eiFaCO5dgvJ48NS4jQMNQTnM7RJilAQLuRo9+iCsY0u+PjbCjXB/TIyE/hqEkjOKKwyTWpscMkL9mrqUHP0ZTkoLE+QGkQWbTueBy27X6BB+F9LocOwNX4eAbROKP8dFlbKbBbWXdEy04mTBCwqjAJeF3I6kvCmo2URP55Jn0v4eex8gZxJcHnuAtmz0jD3kjHJdAwuJAcIaxiHEQc6gQ/b+XvmBNIxLuP8M+2ON+76NnrvKumV/z5uW0AyUHA=
    on:
      tags: true
      repo: james-lim/coin-verse
      branch: develop
  - provider: npm
    email: email@wanseob.com
    api_key:
      secure: fK+YnvRp5Nr2KINC8A6kdc4Wtr7Mn0wRaYhCLviQYa8iMGnekD9qWDG8KPBbY8uKFwqrXTJ7onlB38hLPjiohRGRKYFdclCGUvLGXOT6n5F4sVW+8ZL4cOT3JomePzVUnjW4C913Jv468OKmeLrcTWw/bfRS9sXvzbY0nZKQj6OE7iTp5T+GZEbSAnJjZjah/DHEubKvIW6WtPJ7DvDmHjHssYdLce4wV7FpeBzqh2mfX5MdNfcwa+w8z25VM2VyOnaI7LjsVSMn30IpiVE54jv8SDQ3WzMXeIugmI34+gyW1TDqDdB5Jfa/Nr5aphASSMvDfwlVKiT2K0WRDk0alZuvE7otlZYlwVVTSvIKQ8VYUk3iKETkV0TjFPkOTp26IwNQdY4h1mGLLgZJYRopHDvmxRwBlvB5cxK8oQ9dKgA+HBvJsNoqgv2x1Q1L4eCtC4FPfKYDz8Jc1QjpVKmc6XHle9q/BM05UyTK2c9RtBBVpdkbQz0mPYu6aZOUCSi3zEnPzeiQsQATJUknAkj9EVk0PIYm7OB6UfEQPmV3oOXqoQgYZJIMSpIgXaWxcM3d9O3cJ/AlUHM/+hZotTk5ITuVUW+I+ITrulak+k9pFaIWij/2Dx638J+QHbpxlj9b2nMzI/QNNMAm5vZvMll3gH+N6umPw1PxwmCz77b0OEY=
    tag: latest
    on:
      condition: $LATEST != $CURRENT_VERSION
      branch: master
      repo: james-lim/coin-verse
  - provider: npm
    email: email@wanseob.com
    api_key:
      secure: fK+YnvRp5Nr2KINC8A6kdc4Wtr7Mn0wRaYhCLviQYa8iMGnekD9qWDG8KPBbY8uKFwqrXTJ7onlB38hLPjiohRGRKYFdclCGUvLGXOT6n5F4sVW+8ZL4cOT3JomePzVUnjW4C913Jv468OKmeLrcTWw/bfRS9sXvzbY0nZKQj6OE7iTp5T+GZEbSAnJjZjah/DHEubKvIW6WtPJ7DvDmHjHssYdLce4wV7FpeBzqh2mfX5MdNfcwa+w8z25VM2VyOnaI7LjsVSMn30IpiVE54jv8SDQ3WzMXeIugmI34+gyW1TDqDdB5Jfa/Nr5aphASSMvDfwlVKiT2K0WRDk0alZuvE7otlZYlwVVTSvIKQ8VYUk3iKETkV0TjFPkOTp26IwNQdY4h1mGLLgZJYRopHDvmxRwBlvB5cxK8oQ9dKgA+HBvJsNoqgv2x1Q1L4eCtC4FPfKYDz8Jc1QjpVKmc6XHle9q/BM05UyTK2c9RtBBVpdkbQz0mPYu6aZOUCSi3zEnPzeiQsQATJUknAkj9EVk0PIYm7OB6UfEQPmV3oOXqoQgYZJIMSpIgXaWxcM3d9O3cJ/AlUHM/+hZotTk5ITuVUW+I+ITrulak+k9pFaIWij/2Dx638J+QHbpxlj9b2nMzI/QNNMAm5vZvMll3gH+N6umPw1PxwmCz77b0OEY=
    tag: next
    on:
      condition: $NEXT != $CURRENT_VERSION
      branch: develop
      repo: james-lim/coin-verse
